#!/usr/bin/env python
'''
'''
from roygbiv.server import launch_server
import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="""
                    ROYGBIV is a visualization tool for the outputs of the
                    Mindboggle software.The Mindboggle software automates shape
                    analysis of
                    anatomical labels and features extracted from human brain
                    MR image data (http://mindboggle.info).

                    Example:
                    roygbiv $HOME/freesurfer/subjects/arno""",
                    formatter_class = lambda prog:
                        argparse.HelpFormatter(prog, max_help_position=40))

    parser.add_argument("DATA", help=("path to directory of a person's mindboggle "
                                  "data"))
    args = parser.parse_args()

    launch_server(debug=True, data_dir=args.DATA)
