#!/usr/bin/env python
'''
'''
from roygbiv.server import launch_server
import argparse
import os

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="""
                    ROYGBIV is a visualization tool for the outputs of the
                    Mindboggle software.The Mindboggle software automates shape
                    analysis of
                    anatomical labels and features extracted from human brain
                    MR image data (http://mindboggle.info).

                    Example:
                    roygbiv $HOME/freesurfer/subjects/arno""",
                    formatter_class = lambda prog:
                        argparse.HelpFormatter(prog, max_help_position=40))

    parser.add_argument("DATA", help=("path to directory of a person's mindboggle "
                                  "data"))
    parser.add_argument("-p", "--port", help="port to run server on (default:5000)",
                        default=5000)
    args = parser.parse_args()
    viz_dir = os.path.join(args.DATA,"viz")
    if os.path.exists(args.DATA) and os.path.exists(viz_dir):
        launch_server(debug=True, data_dir=viz_dir, port=int(args.port))
    else:
        raise FileNotFoundError("Cannot find {}/viz".format(args.DATA),
              "please check that it exists and try again")
